config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :path => '', :path_names => {
		:sign_in => '/unicorn'
	}
	resources :posts, :path => 'articles' do
		member do
			put :uplike
		end
  end
	resources :uploads, :path => 'gallery'

  root 'posts#index'

	get 'write', to: redirect('articles/new')

end

app/models/post.rb
class Post
  include Mongoid::Document
	include Mongoid::Slug
	include Mongoid::Timestamps

	field :title, type: String
	field :content, type: String
	field :like, type: Integer,:default => 0

	slug :title
end

app/models/upload.rb
class Upload
  include Mongoid::Document
	include Mongoid::Timestamps

	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show, :index, :uplike]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order_by(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
		@uploads = Upload.order_by(created_at: :desc)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

	def uplike
		set_post
		@post.inc(like: 1)
		respond_to do |format|
      if @post.update(like_params)
        format.html { render :show }
				format.json { render json: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
	end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :like)
    end

		def like_params
			params.permit(:like)
		end


end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	before_action :set_upload, only: [:show, :edit, :update, :destroy]
	# GET /uploads
	def index
		@uploads = Upload.order_by(created_at: :desc)
	end

	# GET /uploads/1
	def show
	end

	# GET /uploads/new
	def new
		@upload = Upload.new
	end

	# GET /uploads/1/edit
	def edit
	end

	# POST /uploads
	def create
		@upload = Upload.new(upload_params)
		respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
	end

	# PATCH/PUT /uploads/1
	def update
		respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
	end

	# DELETE /uploads/1
	def destroy
		@upload.destroy
		respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_upload
			@upload = Upload.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def upload_params
			params.require(:upload).permit(:image) if params[:upload]
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Clean Dates
	def cleandate(date)
      @mo = date.strftime('%b')
      @day = date.strftime('%d')
      @yr = date.strftime('%Y')
      return "#{@mo} #{@day}, #{@yr}"
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/redcarpet_helper.rb
module RedcarpetHelper
	# Markdown Helper
  def markdown(text)
		Redcarpet::Markdown.new(HTMLBlockCode.new(
			:hard_wrap => false,
			:disable_indented_code_blocks => true),
			:filter_html => true,
			:space_after_headers => true,
			:fenced_code_blocks => true,
			:autolink => true,
			:strikethrough => true,
			:prettify => true,
			:superscript => true
		).render(text).html_safe
  end
end


class HTMLBlockCode < Redcarpet::Render::HTML
	include Sprockets::Rails::Helper
  include ActionView::Helpers::UrlHelper

  def image(link, title, alt_text)
		image_tag(link, :class => title, :alt => alt_text)
  end

	def link(link, title, content)
		link_to(content, link, :title => title, :rel => 'nofollow', :target => '_blank')
	end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_header.html.haml
%header{:class => 'masthead', :role => 'banner'}
	.row
		.column.column--1-of-1
			%nav
				= link_to "Home", root_path
				- if user_signed_in?
					= link_to 'Gallery', uploads_path
					= link_to 'Write a story', new_post_path
					= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/layouts/_notice.html.haml
- if flash[:notice]
	.alert.alert--has-success= notice

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title UnicornCms
		%link{rel:'dns-prefetch', href:'//fonts.googleapis.com'}
		%link{href:'//fonts.googleapis.com/css?family=Gentium+Book+Basic|Open+Sans:400,700',rel:'stylesheet', type:'text/css'}
		= stylesheet_link_tag '//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css', 'data-turbolinks-track' => true
		= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.css'
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body{:class => "#{controller_name} #{action_name}"}
		= render 'layouts/header'
		= render 'layouts/notice'
		%main
			= yield
		= render 'layouts/footer'
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.js'

app/views/posts/_form.html.haml
= form_for(@post) do |f|
	- if @post.errors.any?
		#error_explanation
			%h2
				= pluralize(@post.errors.count, "error")
				prohibited this post from being saved:
			%ul
				- @post.errors.full_messages.each do |message|
					%li= message
	%label.sr-only= f.label :title
	= f.text_field :title, class: 'form__input form__input--title', :placeholder => 'Title here'

	%label.sr-only= f.label :content
	= f.text_area :content, style: 'display:none'
	%div
		= f.submit id: 'postSubmit', class: 'sr-only'

app/views/posts/edit.html.haml
.wrapper
	.row
		.column.column--1-of-2.column--centered
			= render 'form'
	= render 'posts/shared/links'

app/views/posts/edit.js.haml
:plain
	$(".index").html("<%= escape_javascript(render('index')) %>")

app/views/posts/index.html.haml
.wrapper
	.row
		.column.column--1-of-2.column--centered
			%h1 Home
			- @posts.each do |post|
				.post__meta
					%small.post__meta--left= cleandate(post.created_at)
					.heart.post__meta--right
						%a{:onclick => "like(this,'#{post.id}')",:href => 'javascript:void(0);', :class => 'heart__link'}
							= image_tag('heart.svg', class: 'heart__img')
						%small{:id => "like_count_#{post.id}", :class => 'heart__number'}= post.like
				%h2{:style => 'margin-top: 0'}
					= link_to post.title, post

app/views/posts/new.html.haml
.wrapper
	.row
		.column.column--1-of-2.column--centered
			= render 'form'
	= render 'posts/shared/links'

app/views/posts/shared/_links.html.haml
%aside.actions
	- if current_page?(action: 'new')
		%label{:for => 'postSubmit', :class => 'button button--primary'} Publish
		%br
		= link_to 'Cancel', posts_path, title: 'Cancel', class: 'button button--default'

	- if controller.action_name != 'new'

		- if current_page?(action: 'show') && user_signed_in?
			= link_to 'Edit', edit_post_path(@post), title: 'Edit'

		- if current_page?(action: 'edit')

			%label{:for => 'postSubmit', :title => 'Update', :class => 'button button--default'} Update
			%br
			= link_to 'Delete',  @post, title: 'Delete',  method: :delete, data: { confirm: 'Are you sure?' }
			%br
			= link_to 'Cancel', @post, title: 'Cancel'

			= render 'posts/shared/uploads'

app/views/posts/shared/_uploads.html.haml
= form_for :upload, :url => uploads_path, html: { multipart: true, class: "dropzone"}, id: 'my-awesome-dropzone', method: :post do |f|
	-# = f.file_field :image

.uploads{:style => 'overflow-y: scroll; height: 250px'}
	.row
		- @uploads.each do |upload|
			.column.column--1-of-2
				= image_tag upload.image.thumb

app/views/posts/shared/_uploads.js.haml
:plain
	$('.uploads').html("#{escape_javascript(render('shared/uploads'))}")

app/views/posts/show.html.haml
-# %button{:id => 'explosion'} Explode
-# %canvas{:id => "canvas_#{@post.id}", :width => '200', :height => '200'}

.wrapper
	.row
		.column.column--1-of-2.column--centered
			- if flash[:notice]
				.alert.alert--has-success= notice
			%article{:role => 'article',
								:itemscope => true,
								:itemtype => 'http://schema.org/Article'}

				%h1.post__title{:itemprop => 'headline'}
					= @post.title
				.post__meta
					%small.post__meta--left= cleandate(@post.created_at)
					.heart.post__meta--right
						%a{:onclick => "like(this,'#{@post.id}')",:href => 'javascript:void(0);', :class => 'heart__link'}
							= image_tag('heart.svg', class: 'heart__img')
						%small{:id => "like_count_#{@post.id}", :class => 'heart__number'}= @post.like
				= markdown(@post.content)
	= render 'posts/shared/links'

app/views/uploads/_form.html.haml
= form_for(@upload) do |f|
	= f.label :image
	= f.file_field :image
	= f.submit

app/views/uploads/index.html.haml
%aside.actions
	= link_to 'New upload', new_upload_path
.wrapper
	.row
		- @uploads.each do |upload|
			.column.column--1-of-5
				= link_to upload do
					%img{:src => upload.image.square, :width => '100%'}

app/views/uploads/new.html.haml
%h1 New Upload
= render 'form'
= link_to 'Back', uploads_path

app/views/uploads/show.html.haml
.wrapper
	.row
		.column.column--2-of-3.column--centered
			.row
				.column.column--1-of-2
					%img{:src => @upload.image.url, :width => '100%'}
					= link_to 'Delete', @upload, class: 'button button--default right',  method: :delete, data: { confirm: 'Are you sure?' }
				.column.column--1-of-2
					%label{:class => 'form__label'} X-Large
					%input{:class => 'form__input', :value => @upload.image.xlarge}
					%label{:class => 'form__label'} Large
					%input{:class => 'form__input', :value => @upload.image.large}
					%label{:class => 'form__label'} Medium
					%input{:class => 'form__input', :value => @upload.image.medium}
					%label{:class => 'form__label'} Thumb
					%input{:class => 'form__input', :value => @upload.image.thumb}
					%label{:class => 'form__label'} Square
					%input{:class => 'form__input', :value => @upload.image.square}